13 suivre trajectoire
Ultime5528/FRC2023 pull request #19
Opened 2023-01-14 06:32 UTC by ThomasMcDonald904

Description
-----------

Closes #13. 
La majorité du code marchait semblait bien, mais pour une étrange raison, rien ne marchait. Des fonction comme `tankDrive(1,1)` ne fesait rien. Après une longue et ardueuse session de _debugging_  j'ai découvert que le _Scheduler_ lui même ne marchait/runnait pas. Ceci affectait le tout du projet, car rien peut fonctionner sans. Ceci est pq à la ligne 22 de robot.py il y a: 
`commands2.CommandScheduler.getInstance().run()`.
Je n'ai pais trouvé comment faire autre chose. D'ailleurs, les années précédante il ne fallait pas faire sa, mystère de la vie I guess. Il y a aussi un essai de faire trajectoire inverse selon les intruction, mais ce n'est pas clair si c'est sa qu'on veut. J'ai anglisiser et corriger des erreures de convention comme les fonction dans base pilotable non-overridden comme `getLeftEncoderPosition` qui doivent être en snake_case: `get_left_encoder_position`
![Simulation](https://user-images.githubusercontent.com/53022931/212459258-22536946-0be0-425a-9b1a-722dafd8bccf.png)

Liste de vérification
---------------------

- Writing conventions :
    - [x] English language
    - [x] File names use lowercase without spaces
    - [x] Class names use PascalCase
    - [x] Function and variable names use snake_case
    - [x] Function and command names start with an action verb (get, set, move, start, stop...)
    - [x] Ports respect the naming convention "subsystem" _ "component type" _ "precision"
    - [x] Properties respect the naming convention
    - [x] ntproperty strings are the same as their variables
- [x] J'ai exécuté tout mon code en simulation.

2023-01-16 22:42 UTC, etiennebeaulac commented
@ThomasMcDonald904 Conflits à résoudre :(

2023-01-16 22:47 UTC, etiennebeaulac requested changes

2023-01-16 22:47 UTC, etiennebeaulac commented on robot.py
> +        # Tu doit mettre ceci sinon le CommandScheduler ne marche pas pour une raison X
Le problème est déjà réglé : il faut juste ne pas mettre de robotPeriodic() puisqu'elle est déjà définie dans TimedCommandRobot. Si jamais on en a besoin, il faudra ajouter super().__init__()

2023-01-16 22:47 UTC, etiennebeaulac commented on subsystems/drivetrain.py
> +        self._motor_left = rev.CANSparkMax(ports.drivetrain_motor_fl, rev.CANSparkMax.MotorType.kBrushless)
Côté lisibilité et considérant que les ports des moteurs ne sont pas souvent utillsés, on pourrait remplacer fl par front_left, rl par rear_left, etc.

2023-01-16 22:47 UTC, etiennebeaulac commented on subsystems/drivetrain.py
> +    def arcade_drive(self, forward: float, rotation: float) -> None:
@Maxence185 a fait remarqué que toutes les fonctions de WPILib sont en camelCase étant donné qu'elles sont importées de C++. Est-ce qu'on devrait changer les conventions pour que les noms de variables demeurent en snake_case, mais que le nom des fonctions et méthodes soient en camelCase? @Adibou16

2023-01-18 22:23 UTC, etiennebeaulac requested changes

2023-01-18 22:23 UTC, etiennebeaulac commented on commands/followtrajectory.py
> +        #         waypoint = Pose2d(waypoint.X() * -1, waypoint.Y() * -1, waypoint.rotation().rotateBy(Rotation2d(math.radians(180))))
Est-ce potentiellement utile ou on peut le supprimer?

2023-01-18 22:23 UTC, etiennebeaulac commented on commands/followtrajectory.py
> +        )
Est-ce qu'on veut ajouter `start_speed` ou `accel` dans `properties.py` ?

2023-01-18 22:23 UTC, etiennebeaulac commented on commands/followtrajectory.py
> +        poseDest = self.states[self.index].pose
snake_case + uniformiser nom de variable avec current_pose

2023-01-18 22:23 UTC, etiennebeaulac commented on commands/followtrajectory.py
> +        currentPose = self.drivetrain.getPose()
snake_case

2023-01-18 22:23 UTC, etiennebeaulac commented on commands/followtrajectory.py
> +            reset: bool = False,
`reset` n'est plus utilisé

2023-01-18 22:23 UTC, etiennebeaulac commented on commands/followtrajectory.py
> +    FollowTrajectory(self.drivetrain, [self.drivetrain.get_pose(), Pose2d(0, 3, 90), Pose2d(3, 3, 0)], 0.5)
`get_pose()` a-t-il renommé en `getPose()` ?

2023-01-18 22:23 UTC, etiennebeaulac commented on commands/followtrajectory.py
> +        traversed = self.states[0].pose.translation().distance(poseDest.translation())
`traversed` n'est pas clair comme nom de variable

2023-01-18 22:23 UTC, etiennebeaulac commented on commands/followtrajectory.py
> +        correction = values.trajectory_correction_angle * error.degrees()
Ne pas importer `values` de `properties`, juste importer `properties` et écrire `properties.values.trajectory_correction_angle`

2023-01-18 22:23 UTC, etiennebeaulac commented on requirements.txt
> +opencv-python==4.5.5.62
N'est plus utilisé

2023-01-18 22:23 UTC, etiennebeaulac commented on requirements.txt
> +pynetworktables==2021.0.0
N'existe plus en 2023, a été remplacé par `ntcore` et déjà inclus (c'est pourquoi la version est 2021 je crois)

2023-01-18 22:23 UTC, etiennebeaulac commented on robot.py
> +from networktables import NetworkTables
N'existe plus en 2023, ce n'est pas supposé fonctionné. C'est pourquoi il faut enlever `pynetworktables` des requirements.

2023-01-18 22:23 UTC, etiennebeaulac commented on robot.py
> +        NetworkTables.initialize("127.0.0.1")
Ce n'est pas nécessaire

2023-01-18 22:23 UTC, etiennebeaulac commented on subsystems/drivetrain.py
> +            motor.restoreFactoryDefaults()
`restoreFactoryDefaults` est déjà appelé par `configure_leader` et `configure_follower`, il ne faut pas le réutiliser ici, sinon on enlève toute la configuration faite précédemment.

2023-01-18 22:23 UTC, etiennebeaulac commented on utils/trapezoidalmotion.py
> +    def set_position(self, position: float):
camelCase

2023-01-18 22:23 UTC, etiennebeaulac commented on utils/trapezoidalmotion.py
> +    def get_speed(self) -> float:
camelCase

2023-01-18 22:37 UTC, ThomasMcDonald904 commented on commands/followtrajectory.py
> +        )
Oui

2023-01-19 00:39 UTC, etiennebeaulac requested changes

2023-01-19 00:39 UTC, etiennebeaulac commented on commands/drive.py
> -        self.setName("Drive")
`addRequirements` est nécessaire! Mais `setName` peut rester supprimer, c'est fait automatiquement par `SafeCommandBase`.

2023-01-19 00:39 UTC, etiennebeaulac commented on properties.py
> +    trajectory_acceleration = ntproperty("/Properties/trajectory_acceleration", 0.08, writeDefault=False, persistent=persistent)
Ne respecte pas les conventions de properties `command-name_type-variable_precision`

2023-01-21 15:34 UTC, etiennebeaulac approved these changes

2023-01-21 15:34 UTC, merged