28 led
Ultime5528/FRC2023 pull request #80
Opened 2023-02-11 16:58 UTC by Quexi05

Description
-----------
Appliquer les conventions, changer la couleur durant le mode autonome et enlever certains éléments de l'année passée
Closes #TODO. 

Liste de vérification
---------------------

- Writing conventions :
    - [x] English language
    - [x] File names use lowercase without spaces
    - [x] Class names use PascalCase
    - [x] Functions use camelCase
    - [x] Variable names use snake_case
    - [x] Function and command names start with an action verb (get, set, move, start, stop...)
    - [x] Ports respect the naming convention "subsystem" _ "component type" _ "precision"
    - [x] Properties respect the naming convention
- Command and subsytem safety :
    - [x] Commands and subsystems inherit from SafeCommand and SafeSubsystem
    - [x] No commands or subsytems have a `setName()` method, unless necessary
    - [x] Commands have a `addRequirements()` method that includes all the subsystems they use
- [x] J'ai exécuté tout mon code en simulation.

2023-02-25 20:59 UTC, etiennebeaulac requested changes

2023-02-25 20:59 UTC, etiennebeaulac commented on commands/signalcone.py
> +        self.led_controller.black
Cette ligne ne fait rien.

2023-02-25 20:59 UTC, etiennebeaulac commented on commands/signalcube.py
> +        self.led_controller.black
Idem, cette ligne ne fait rien.

2023-02-25 20:59 UTC, etiennebeaulac commented on robot.py
> +
Seulement deux whitespaces.

2023-02-25 20:59 UTC, etiennebeaulac commented on subsystems/led.py
> +        self.buffer = [wpilib.AddressableLED.LEDData() for _ in range(300)]
Mettre le nombre de LED dans une constante en haut (comme les couleurs) et le changer pour le bon chiffre (plus petit que 300 cette année).

2023-02-25 20:59 UTC, etiennebeaulac commented on subsystems/led.py
> +                self.mode = ModeLED.CONE
Pourquoi convertir un str en enum? Simplement utiliser l'enum.

2023-02-25 20:59 UTC, etiennebeaulac commented on subsystems/led.py
> +    def setMode(self, mode: str):
```suggestion
    def setMode(self, mode: ModeLED):
```

2023-02-25 20:59 UTC, etiennebeaulac commented on subsystems/led.py
> +
Une seule ligne vide est suffisante.

2023-02-25 20:59 UTC, etiennebeaulac commented on commands/signalcone.py
> +        self.duration = 2
Devrait être une propriété.

2023-02-25 20:59 UTC, etiennebeaulac commented on commands/signalcube.py
> +        self.duration = 2
Devrait être une propriété.

2023-02-25 20:59 UTC, etiennebeaulac commented on subsystems/led.py
> +    pink = np.array([15, 120, 255])
Est-ce que toutes ces couleurs sont utilisées ?

2023-02-25 20:59 UTC, etiennebeaulac commented on subsystems/led.py
> +
Inutilisée ?

2023-02-25 20:59 UTC, etiennebeaulac commented on subsystems/led.py
> +
Inutilisée ?

2023-02-25 20:59 UTC, etiennebeaulac commented on subsystems/led.py
> +        return self.setAll(getColor)
Inutilisée ?

2023-03-06 23:15 UTC, Adibou16 commented on subsystems/led.py
> +    pink = np.array([15, 120, 255])
Oui, sauf le blanc

2023-03-11 17:18 UTC, merged